#!/bin/bash

set -e

cd "$(dirname "$0")/../builtinFonts"

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""
echo "// Pridi font IDs - unique identifiers based on font data hash"
echo "// Only Regular and Bold styles (no Italic variants for Pridi)"

echo "#define PRIDI_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./pridi_12_regular.h",
  "./pridi_12_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define PRIDI_14_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./pridi_14_regular.h",
  "./pridi_14_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define PRIDI_16_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./pridi_16_regular.h",
  "./pridi_16_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define PRIDI_18_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./pridi_18_regular.h",
  "./pridi_18_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_10_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./pridi_10_regular.h",
  "./pridi_10_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./pridi_12_regular.h",
  "./pridi_12_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define SMALL_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./pridi_8_regular.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"
