#!/bin/bash

set -e

cd "$(dirname "$0")/../builtinFonts"

echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""
echo "// System font IDs - unique identifiers based on font data hash"
echo "// Only Regular and Bold styles (no Italic variants)"

echo "#define SYSTEM_FONT_12_ID ($(
ruby -rdigest -e 'puts [
  "./system_font_12_regular.h",
  "./system_font_12_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define SYSTEM_FONT_14_ID ($(
ruby -rdigest -e 'puts [
  "./system_font_14_regular.h",
  "./system_font_14_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define SYSTEM_FONT_16_ID ($(
ruby -rdigest -e 'puts [
  "./system_font_16_regular.h",
  "./system_font_16_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define SYSTEM_FONT_18_ID ($(
ruby -rdigest -e 'puts [
  "./system_font_18_regular.h",
  "./system_font_18_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_10_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./system_font_10_regular.h",
  "./system_font_10_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define UI_12_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./system_font_12_regular.h",
  "./system_font_12_bold.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"

echo "#define SMALL_FONT_ID ($(
ruby -rdigest -e 'puts [
  "./system_font_8_regular.h",
].map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16) }.sum % (2 ** 32) - (2 ** 31)'
))"
