// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

// Pridi font IDs - unique identifiers based on font data hash
#define PRIDI_12_FONT_ID (1)
#define PRIDI_14_FONT_ID (2)
#define PRIDI_16_FONT_ID (3)
#define PRIDI_18_FONT_ID (4)
#define UI_10_FONT_ID (5)
#define UI_12_FONT_ID (6)
#define SMALL_FONT_ID (7)
