// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

// System font IDs - unique identifiers based on font data hash
// Only Regular and Bold styles (no Italic variants)
#define SYSTEM_FONT_12_ID (-523365562)
#define SYSTEM_FONT_14_ID (1263960431)
#define SYSTEM_FONT_16_ID (-1430406635)
#define SYSTEM_FONT_18_ID (664921716)
#define UI_10_FONT_ID (262814919)
#define UI_12_FONT_ID (-523365562)
#define SMALL_FONT_ID (1865078121)
