name: CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Install clang-format
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format
          clang-format --version

      - name: Run cppcheck
        run: pio check --fail-on-defect low --fail-on-defect medium --fail-on-defect high

      - name: Run clang-format
        run: PATH="/usr/lib/llvm-21/bin:$PATH" ./bin/clang-format-fix && git diff --exit-code || (echo "Please run 'bin/clang-format-fix' to fix formatting issues" && exit 1)

      - name: Build CrossPoint
        run: pio run
